#man:
#  age: 020123123123
#
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.117.1301:3306/test1?characterEncoding=utf-8&useSSL=false
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456aA!
#  jpa:
#    show-sql: true
#  application:
#    name: will