spring:
  datasource:
    url: jdbc:mysql://192.168.165.34:3306/test1?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: my_passwd
  jpa:
    show-sql: true
  application:
    name: will